Server:
  host: "0.0.0.0"
  port: "8080"
  writeTimeout: 15
  readTimeout: 15
Bot:
  token:
Storage:
  host: "postgres"
  port: "5432"
  database: "tgsender"
  username: "admin"
  password: "admin"
  maxAttempt: 2