version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_DB: "tgsender"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    volumes:
      - ./entrypoint.d:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U admin -d tgsender" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 4G
    networks:
      - postgresnet

#  pgadmin:
#    container_name: pgadmin_container
#    platform: linux/amd64
#    image: dpage/pgadmin4:latest
#    environment:
#      PGADMIN_DEFAULT_EMAIL: "pgadmin@pg.com"
#      PGADMIN_DEFAULT_PASSWORD: "pgadminpwd4"
#      PGADMIN_CONFIG_SERVER_MODE: "False"
#    volumes:
#      - ./pgadmin:/var/lib/pgadmin
#    ports:
#      - "5050:80"
#    restart: unless-stopped
#    deploy:
#      resources:
#        limits:
#          cpus: '0.5'
#          memory: 1G
#    depends_on:
#      - postgres
#    networks:
#      - postgresnet

  server:
    container_name: server_container
    build: ../Server/
    restart: on-failure
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    networks:
      - postgresnet

networks:
  postgresnet:
    driver: bridge